export const TestsCardData = [
  {
    topic: 'Kinematics',
    duration: '3 hours • 21st May 2024',
    totalMarks: 100,
    location: 'Sector 17, Chandigarh',
    seats: '35/50',
    price: '1500',
    refundable: 'refundable',
  },
  {
    topic: 'Thermodynamics',
    duration: '2.5 hours',
    totalMarks: 80,
    location: 'Sector 12, Noida',
    seats: '45/60',
    price: '2500',
    refundable: 'non-refundable',
  },
  {
    topic: 'Integration',
    duration: '4 hours',
    totalMarks: 120,
    location: 'Sector 25, Gurgaon',
    seats: '20/30',
    price: '3000',
    refundable: 'refundable',
  },
  {
    topic: 'Chemical Equilibrium',
    duration: '3.5 hours',
    totalMarks: 90,
    location: 'Sector 16, Faridabad',
    seats: '25/40',
    price: '2000',
    refundable: 'non-refundable',
  },
  {
    topic: 'Vectors',
    duration: '4 hours',
    totalMarks: 100,
    location: 'Sector 22, Mohali',
    seats: '15/20',
    price: '1800',
    refundable: 'refundable',
  },
  {
    topic: 'Algebra',
    duration: '3 hours',
    totalMarks: 80,
    location: 'Sector 10, Dwarka, New Delhi',
    seats: '10/15',
    price: '3200',
    refundable: 'non-refundable',
  },
  {
    topic: 'Atomic Structure',
    duration: '2 hours',
    totalMarks: 70,
    location: 'Sector 11, Rohini, New Delhi',
    seats: '30/50',
    price: '2700',
    refundable: 'refundable',
  },
  {
    topic: 'Differential Equations',
    duration: '3 hours',
    totalMarks: 90,
    location: 'Sector 8, Pimpri-Chinchwad, Pune',
    seats: '20/25',
    price: '4000',
    refundable: 'non-refundable',
  },
  {
    topic: 'Chemical Kinetics',
    duration: '6 hours',
    totalMarks: 120,
    location: 'Sector 7, HSR Layout, Bangalore',
    seats: '50/100',
    price: '1900',
    refundable: 'refundable',
  },
  {
    topic: 'Probability',
    duration: '2 hours',
    totalMarks: 80,
    location: 'Sector 6, Salt Lake City, Kolkata',
    seats: '40/50',
    price: '3500',
    refundable: 'non-refundable',
  },
];
